// Chat screen for React Native (generated by the ethora-skill).
// Mount it as a screen (React Navigation) or a route file (Expo Router: app/chat.tsx → export default EthoraChatScreen).
import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { Chat, XmppProvider } from '@ethora/chat-component-rn';
import { ETHORA, buildEthoraConfig } from './ethora.config';

type Props = {
  roomJID?: string;
  /** Pass a token you already have; otherwise it is fetched from ETHORA.tokenEndpoint. */
  clientJwt?: string;
  /** For tab hosts that keep the screen mounted while hidden (unread tracking). */
  isVisible?: boolean;
};

export default function EthoraChatScreen({ roomJID, clientJwt, isVisible }: Props) {
  const [token, setToken] = useState<string | null>(clientJwt ?? ETHORA.devClientJwt ?? null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (token) return;
    let cancelled = false;
    // Send your app's own session (cookie / bearer) so the backend knows which user to mint a token for.
    fetch(ETHORA.tokenEndpoint, { headers: { /* Authorization: `Bearer ${yourSessionToken}` */ } })
      .then(async (r) => { if (!r.ok) throw new Error(`${r.status} ${await r.text()}`); return r.json(); })
      .then((d: { token: string }) => { if (!cancelled) setToken(d.token); })
      .catch((e) => { if (!cancelled) setError(String(e.message || e)); });
    return () => { cancelled = true; };
  }, [token]);

  const config = useMemo(() => buildEthoraConfig(token), [token]);

  if (error) return <View style={styles.center}><Text>Chat is unavailable: {error}</Text></View>;
  if (!token) return <View style={styles.center}><ActivityIndicator /></View>;

  return (
    <SafeAreaView style={styles.root}>
      <XmppProvider config={config}>
        <Chat config={config} roomJID={roomJID} isVisible={isVisible} />
      </XmppProvider>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 16 },
});
