// Chat screen for React Native (generated by the ethora-skill).
// Mount it as a screen (React Navigation) or a route file (Expo Router: app/chat.tsx → export default EthoraChatScreen).
//
// Do NOT wrap <Chat> in your own <XmppProvider>: <Chat> already mounts the SDK's redux store AND its own
// XmppProvider (true for 26.4.x and 26.9.x). Since 26.9.x an outer XmppProvider renders the video-call overlay
// outside the redux store and crashes with "could not find react-redux context value".
import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Chat } from '@ethora/chat-component-rn';
import { ETHORA, buildEthoraConfig } from './ethora.config';

type Props = {
  roomJID?: string;
  /** Pass a token you already have; otherwise it is fetched from ETHORA.tokenEndpoint. */
  clientJwt?: string;
  /** Your app's own session token, sent as `Authorization: Bearer …` to the token endpoint. */
  sessionToken?: string | null;
  /** For tab hosts that keep the screen mounted while hidden (unread tracking).
   *  Expo Router: `useIsFocused` from 'expo-router'; React Navigation: from '@react-navigation/native'. */
  isVisible?: boolean;
};

export default function EthoraChatScreen({ roomJID, clientJwt, sessionToken, isVisible }: Props) {
  const [token, setToken] = useState<string | null>(clientJwt ?? ETHORA.devClientJwt ?? null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (token) return;
    let cancelled = false;
    // The backend must know WHICH user to mint a token for: send your app's session.
    fetch(ETHORA.tokenEndpoint, { headers: sessionToken ? { Authorization: `Bearer ${sessionToken}` } : {} })
      .then(async (r) => { if (!r.ok) throw new Error(`${r.status} ${await r.text()}`); return r.json(); })
      .then((d: { token: string }) => { if (!cancelled) setToken(d.token); })
      .catch((e) => { if (!cancelled) setError(String(e.message || e)); });
    return () => { cancelled = true; };
  }, [token, sessionToken]);

  const config = useMemo(() => buildEthoraConfig(token), [token]);

  if (error) return <View style={styles.center}><Text>Chat is unavailable: {error}</Text></View>;
  if (!token) return <View style={styles.center}><ActivityIndicator /></View>;

  return (
    <SafeAreaView style={styles.root} edges={['top']}>
      <Chat config={config} roomJID={roomJID} isVisible={isVisible} />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 16 },
});
