// Ethora chat config for React Native (generated by the ethora-skill).
// Expo: values come from EXPO_PUBLIC_* in .env (written by write-env.mjs --target expo).
// Bare RN: write-env.mjs --target rn generates src/ethora.config.ts with literals instead of this file.
import type { ComponentProps } from 'react';
import type { Chat } from '@ethora/chat-component-rn';

type IConfig = NonNullable<ComponentProps<typeof Chat>['config']>;

export const ETHORA = {
  appId: process.env.EXPO_PUBLIC_ETHORA_APP_ID ?? '',
  appToken: process.env.EXPO_PUBLIC_ETHORA_APP_TOKEN ?? '',
  apiUrl: process.env.EXPO_PUBLIC_ETHORA_API_URL ?? 'https://api.chat.ethora.com',
  xmppHost: process.env.EXPO_PUBLIC_ETHORA_XMPP_HOST ?? 'xmpp.chat.ethora.com',
  xmppConference: process.env.EXPO_PUBLIC_ETHORA_XMPP_CONFERENCE ?? 'conference.xmpp.chat.ethora.com',
  /** Your backend endpoint returning `{ token }` (client JWT for the signed-in user). Absolute URL on mobile! */
  tokenEndpoint: process.env.EXPO_PUBLIC_ETHORA_TOKEN_ENDPOINT ?? 'https://your-backend.example.com/api/ethora/token',
  /** DEV ONLY: pre-signed client JWT for a test user. */
  devClientJwt: process.env.EXPO_PUBLIC_ETHORA_DEV_CLIENT_JWT,
};

/** Same object for <XmppProvider> and <Chat> (single XMPP init contract). */
export function buildEthoraConfig(clientJwt: string | null): IConfig {
  return {
    appId: ETHORA.appId,
    customAppToken: ETHORA.appToken,
    baseUrl: ETHORA.apiUrl,
    xmppSettings: {
      devServer: ETHORA.xmppHost, // RN: bare host — the SDK builds wss://<host>/ws itself
      host: ETHORA.xmppHost,
      conference: ETHORA.xmppConference,
    },
    initBeforeLoad: true,
    newArch: true,
    refreshTokens: { enabled: true },
    ...(clientJwt ? { jwtLogin: { enabled: true, token: clientJwt } } : {}),
    colors: { primary: '#0052CD', secondary: '#E8F0FE' },
  };
}
