// Next.js App Router: app/api/ethora/token/route.ts (generated by the ethora-skill)
// Mints a client JWT for the signed-in user. Replace `getCurrentUser` with your auth (next-auth, Clerk, cookies…).
import { NextResponse } from 'next/server';
import { createHmac } from 'node:crypto';

const APP_ID = process.env.ETHORA_APP_ID!;
const APP_SECRET = process.env.ETHORA_APP_SECRET!;
const API_URL = (process.env.ETHORA_API_URL || 'https://api.chat.ethora.com').replace(/\/v[12]\/?$/, '');

const b64url = (b: string | Buffer) => Buffer.from(b).toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
function sign(payload: object) {
  const h = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const b = b64url(JSON.stringify(payload));
  return `${h}.${b}.${b64url(createHmac('sha256', APP_SECRET).update(`${h}.${b}`).digest())}`;
}

async function getCurrentUser(_req: Request): Promise<{ id: string; email: string; firstName?: string; lastName?: string } | null> {
  // TODO: read your session here. Example for a demo: a fixed user.
  return { id: 'demo-user-1', email: 'demo-user-1@example.com', firstName: 'Demo', lastName: 'User' };
}

const ensured = new Set<string>();
async function ensureEthoraUser(u: { id: string; email: string; firstName?: string; lastName?: string }) {
  if (ensured.has(u.id)) return;
  const now = Math.floor(Date.now() / 1000);
  const res = await fetch(`${API_URL}/v1/users/batch`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-custom-token': sign({ data: { type: 'server', appId: APP_ID }, iat: now, exp: now + 600 }) },
    body: JSON.stringify({ bypassEmailConfirmation: true, usersList: [{ uuid: u.id, email: u.email, firstName: u.firstName || 'User', lastName: u.lastName || '' }] }),
  });
  if (!res.ok && !/exist|already|duplicate/i.test(await res.text())) throw new Error('Ethora user sync failed');
  ensured.add(u.id);
}

export async function GET(req: Request) {
  if (!APP_ID || !APP_SECRET) return NextResponse.json({ error: 'ETHORA_APP_ID / ETHORA_APP_SECRET not configured' }, { status: 500 });
  const user = await getCurrentUser(req);
  if (!user) return NextResponse.json({ error: 'unauthenticated' }, { status: 401 });
  await ensureEthoraUser(user);
  const now = Math.floor(Date.now() / 1000);
  const token = sign({ data: { type: 'client', appId: APP_ID, userId: user.id }, iat: now, exp: now + 12 * 3600 });
  return NextResponse.json({ token });
}
