// Example page (generated by the ethora-skill). Register it in your router, e.g.
//   react-router:  <Route path="/chat" element={<ChatPage />} />
//   Next app router: app/chat/page.tsx → export default function Page() { return <ChatPage />; }  (import EthoraChatNext there)
import EthoraChat from './EthoraChat';

export default function ChatPage() {
  return (
    <main style={{ height: '100vh', display: 'flex', flexDirection: 'column' }}>
      <EthoraChat style={{ flex: 1 }} />
    </main>
  );
}
