'use client';
// Next.js wrapper (generated by the ethora-skill): the chat touches window/WebSocket, so it must never render on the server.
import dynamic from 'next/dynamic';

const EthoraChat = dynamic(() => import('./EthoraChat'), {
  ssr: false,
  loading: () => <div style={{ padding: 16 }}>Loading chat…</div>,
});

export default EthoraChat;
