// Drop-in chat block (generated by the ethora-skill).
// Usage: <EthoraChat />  — or <EthoraChat roomJID="room@conference.xmpp.chat.ethora.com" /> for a single room.
//
// Auth: fetches a client JWT for the current signed-in user from your backend (ETHORA.tokenEndpoint),
// then renders the chat already logged in (no Ethora login screen). See references/auth-modes.md.
import { useEffect, useMemo, useState } from 'react';
import { Chat, XmppProvider } from '@ethora/chat-component';
import '@ethora/chat-component/dist/main.css';
import { ETHORA, buildEthoraConfig } from './ethora.config';

type Props = {
  roomJID?: string;
  /** Pass a token you already have; otherwise it is fetched from ETHORA.tokenEndpoint. */
  clientJwt?: string;
  style?: React.CSSProperties;
};

export default function EthoraChat({ roomJID, clientJwt, style }: Props) {
  const [token, setToken] = useState<string | null>(clientJwt ?? ETHORA.devClientJwt ?? null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (token) return;
    let cancelled = false;
    fetch(ETHORA.tokenEndpoint, { credentials: 'include' })
      .then(async (r) => {
        if (!r.ok) throw new Error(`${r.status} ${await r.text()}`);
        return r.json();
      })
      .then((d: { token: string }) => { if (!cancelled) setToken(d.token); })
      .catch((e) => { if (!cancelled) setError(String(e.message || e)); });
    return () => { cancelled = true; };
  }, [token]);

  // One memoized config object for BOTH provider and chat (single XMPP init).
  const config = useMemo(() => buildEthoraConfig(token), [token]);

  if (error) return <div style={{ padding: 16 }}>Chat is unavailable: {error}</div>;
  if (!token) return <div style={{ padding: 16 }}>Connecting to chat…</div>;

  return (
    <div style={{ height: '100%', minHeight: 480, ...style }}>
      <XmppProvider config={config}>
        <Chat config={config} roomJID={roomJID} MainComponentStyles={{ height: '100%' }} />
      </XmppProvider>
    </div>
  );
}
