// Ethora chat config for the browser (generated by the ethora-skill).
// Values come from the public env vars written by `write-env.mjs`.
//
//   Vite  → import.meta.env.VITE_ETHORA_*          (this file as-is)
//   Next  → process.env.NEXT_PUBLIC_ETHORA_*        (replace the `import.meta.env.VITE_` reads with literal process.env.NEXT_PUBLIC_ keys)
//   CRA   → process.env.REACT_APP_ETHORA_*          (same, literal keys — CRA/Next inline only literal lookups)
import type { ComponentProps } from 'react';
import type { Chat } from '@ethora/chat-component';

export type EthoraConfig = NonNullable<ComponentProps<typeof Chat>['config']>;

export const ETHORA = {
  appId: import.meta.env.VITE_ETHORA_APP_ID ?? '',
  appToken: import.meta.env.VITE_ETHORA_APP_TOKEN ?? '',
  apiUrl: import.meta.env.VITE_ETHORA_API_URL ?? 'https://api.chat.ethora.com',
  xmppHost: import.meta.env.VITE_ETHORA_XMPP_HOST ?? 'xmpp.chat.ethora.com',
  xmppWs: import.meta.env.VITE_ETHORA_XMPP_WS ?? 'wss://xmpp.chat.ethora.com/ws',
  xmppConference: import.meta.env.VITE_ETHORA_XMPP_CONFERENCE ?? 'conference.xmpp.chat.ethora.com',
  /** Your backend endpoint that returns `{ token }` — a client JWT for the signed-in user. */
  tokenEndpoint: '/api/ethora/token',
  /** DEV ONLY: pre-signed client JWT for a test user (never ship this). */
  devClientJwt: import.meta.env.VITE_ETHORA_DEV_CLIENT_JWT as string | undefined,
};

/**
 * Base config shared by <XmppProvider> and <Chat>. Keep it memoized and pass the SAME object to both
 * (single XMPP initialization contract — otherwise you get two websocket connections).
 */
export function buildEthoraConfig(clientJwt: string | null): EthoraConfig {
  return {
    appId: ETHORA.appId,
    customAppToken: ETHORA.appToken,
    baseUrl: ETHORA.apiUrl,
    xmppSettings: {
      devServer: ETHORA.xmppWs, // web: full wss:// URL
      host: ETHORA.xmppHost,
      conference: ETHORA.xmppConference,
    },
    initBeforeLoad: true,
    newArch: true,
    refreshTokens: { enabled: true },
    ...(clientJwt ? { jwtLogin: { enabled: true, token: clientJwt } } : {}),
    colors: { primary: '#0052CD', secondary: '#E8F0FE' },
  };
}
