// DEV-ONLY Vite plugin (generated by the ethora-skill): serves GET /api/ethora/token from the dev server
// so a frontend-only project can try the "no login screen" flow without a backend.
// The secret is read from .env.ethora (ETHORA_APP_SECRET) at dev time and never reaches the browser bundle.
//
// vite.config.ts:
//   import { ethoraDevToken } from './vite-dev-token-plugin';
//   export default defineConfig({ plugins: [react(), ethoraDevToken({ userId: 'dev-user-1', email: 'dev-user-1@example.com' })] });
import { createHmac } from 'node:crypto';
import { readFileSync } from 'node:fs';
import type { Plugin } from 'vite';

function readDotenv(file: string): Record<string, string> {
  try {
    return Object.fromEntries(readFileSync(file, 'utf8').split('\n').filter((l) => /^[A-Z_]+=/.test(l)).map((l) => { const i = l.indexOf('='); return [l.slice(0, i), l.slice(i + 1)]; }));
  } catch { return {}; }
}
const b64url = (b: string | Buffer) => Buffer.from(b).toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
const sign = (payload: object, secret: string) => { const h = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' })); const b = b64url(JSON.stringify(payload)); return `${h}.${b}.${b64url(createHmac('sha256', secret).update(`${h}.${b}`).digest())}`; };

export function ethoraDevToken(opts: { userId: string; email: string; firstName?: string; lastName?: string; envFile?: string }): Plugin {
  let ensured = false;
  return {
    name: 'ethora-dev-token',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/api/ethora/token', async (_req, res) => {
        const env = readDotenv(opts.envFile || '.env.ethora');
        const appId = env.ETHORA_APP_ID; const secret = env.ETHORA_APP_SECRET;
        const api = (env.ETHORA_API_BASE_URL || 'https://api.chat.ethora.com').replace(/\/v[12]\/?$/, '');
        if (!appId || !secret) { res.statusCode = 500; res.end('ETHORA_APP_ID / ETHORA_APP_SECRET missing in .env.ethora'); return; }
        const now = Math.floor(Date.now() / 1000);
        if (!ensured) {
          const r = await fetch(`${api}/v1/users/batch`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-custom-token': sign({ data: { type: 'server', appId }, iat: now, exp: now + 600 }, secret) }, body: JSON.stringify({ bypassEmailConfirmation: true, usersList: [{ uuid: opts.userId, email: opts.email, firstName: opts.firstName || 'Dev', lastName: opts.lastName || 'User' }] }) });
          if (r.ok || /exist|already|duplicate/i.test(await r.text())) ensured = true;
        }
        res.setHeader('Content-Type', 'application/json');
        res.end(JSON.stringify({ token: sign({ data: { type: 'client', appId, userId: opts.userId }, iat: now, exp: now + 12 * 3600 }, secret) }));
      });
    },
  };
}
