#!/usr/bin/env node
/**
 * write-env.mjs — write Ethora config into a project from the active profile.
 *
 * Usage:
 *   node write-env.mjs --target <vite|next|cra|expo|rn|backend|dotenv> [--dir <projectDir>] [--profile <name>]
 *                      [--dev-jwt <token>]  (web/expo only: dev-time client JWT for a test user)
 *
 * Targets and what gets written (existing keys are updated, others kept):
 *   vite     .env.local   VITE_ETHORA_*            (public: app id, app token, endpoints)
 *   next     .env.local   NEXT_PUBLIC_ETHORA_* + ETHORA_APP_SECRET (server-only, for the token route)
 *   cra      .env.local   REACT_APP_ETHORA_*
 *   expo     .env         EXPO_PUBLIC_ETHORA_*
 *   rn       src/ethora.config.ts   (bare React Native: literal config module, no secret)
 *   backend  .env         ETHORA_APP_ID, ETHORA_APP_SECRET, ETHORA_API_URL   (server only)
 *   dotenv   .env.ethora  same format as `npx @ethora/setup` (everything, incl. secret)
 *
 * The app secret is NEVER written with a public prefix (VITE_/NEXT_PUBLIC_/EXPO_PUBLIC_/REACT_APP_).
 * Env files are added to .gitignore when missing.
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync, appendFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve, dirname } from 'node:path';

const argv = process.argv.slice(2);
const flag = (n) => { const i = argv.indexOf('--' + n); return i >= 0 ? argv[i + 1] : undefined; };
const target = flag('target');
const dir = resolve(flag('dir') || process.cwd());
const devJwt = flag('dev-jwt');
if (!target) { console.error('Usage: write-env.mjs --target <vite|next|cra|expo|rn|backend|dotenv> [--dir d] [--profile p]'); process.exit(1); }

const store = (() => { try { return JSON.parse(readFileSync(join(process.env.ETHORA_HOME || join(homedir(), '.ethora'), 'profiles.json'), 'utf8')); } catch { return null; } })();
const profileName = flag('profile') || store?.activeProfile;
const profile = store?.profiles?.[profileName];
if (!profile) { console.error('No active Ethora profile. Run: node ethora-admin.mjs setup'); process.exit(1); }
const e = profile.endpoints;
const apiOrigin = String(e.apiUrl).replace(/\/v[12]\/?$/, '');
const xmppHost = e.xmppHost;

const publicValues = (prefix) => ({
  [`${prefix}ETHORA_APP_ID`]: profile.appId,
  [`${prefix}ETHORA_APP_TOKEN`]: profile.appToken,
  [`${prefix}ETHORA_API_URL`]: apiOrigin,
  [`${prefix}ETHORA_XMPP_HOST`]: xmppHost,
  [`${prefix}ETHORA_XMPP_WS`]: e.xmppWebSocket,
  [`${prefix}ETHORA_XMPP_CONFERENCE`]: e.xmppConference,
  ...(devJwt ? { [`${prefix}ETHORA_DEV_CLIENT_JWT`]: devJwt } : {}),
});
const serverValues = () => ({
  ETHORA_APP_ID: profile.appId,
  ETHORA_APP_SECRET: profile.appSecret || '',
  ETHORA_API_URL: apiOrigin,
});

function mergeEnv(file, values, header) {
  const path = join(dir, file);
  let content = existsSync(path) ? readFileSync(path, 'utf8') : '';
  const lines = content.split('\n');
  const seen = new Set();
  const out = lines.map((line) => {
    const m = line.match(/^\s*(?:export\s+)?([A-Z0-9_]+)\s*=/);
    if (m && values[m[1]] !== undefined) { seen.add(m[1]); return `${m[1]}=${values[m[1]]}`; }
    return line;
  });
  const missing = Object.keys(values).filter((k) => !seen.has(k));
  if (missing.length) {
    if (out.length && out[out.length - 1] !== '') out.push('');
    if (header && !content.includes(header)) out.push(header);
    for (const k of missing) out.push(`${k}=${values[k]}`);
    out.push('');
  }
  writeFileSync(path, out.join('\n'));
  return path;
}
function ensureGitignore(entry) {
  const gi = join(dir, '.gitignore');
  const cur = existsSync(gi) ? readFileSync(gi, 'utf8') : '';
  if (!cur.split('\n').some((l) => l.trim() === entry)) appendFileSync(gi, `${cur.endsWith('\n') || !cur ? '' : '\n'}${entry}\n`);
}

const written = [];
switch (target) {
  case 'vite':
    written.push(mergeEnv('.env.local', publicValues('VITE_'), '# Ethora chat (generated by the ethora-skill)')); ensureGitignore('.env.local'); break;
  case 'cra':
    written.push(mergeEnv('.env.local', publicValues('REACT_APP_'), '# Ethora chat (generated by the ethora-skill)')); ensureGitignore('.env.local'); break;
  case 'next':
    written.push(mergeEnv('.env.local', { ...publicValues('NEXT_PUBLIC_'), ...serverValues() }, '# Ethora chat (generated by the ethora-skill). ETHORA_APP_SECRET is server-only.')); ensureGitignore('.env.local'); break;
  case 'expo':
    written.push(mergeEnv('.env', publicValues('EXPO_PUBLIC_'), '# Ethora chat (generated by the ethora-skill)')); ensureGitignore('.env'); break;
  case 'backend':
    written.push(mergeEnv('.env', serverValues(), '# Ethora server credentials (generated by the ethora-skill) — never ship to a client')); ensureGitignore('.env'); break;
  case 'dotenv': {
    const content = [
      '# Ethora SDK Configuration', `# Profile: ${profile.name} (${profile.type})`, '# Generated by the ethora-skill (same format as @ethora/setup)', '',
      `ETHORA_APP_ID=${profile.appId}`, `ETHORA_APP_TOKEN=${profile.appToken}`, `ETHORA_APP_SECRET=${profile.appSecret || ''}`,
      `ETHORA_APP_DOMAIN_NAME=${profile.domainName || ''}`, `ETHORA_API_BASE_URL=${e.apiUrl}`, `ETHORA_XMPP_HOST=${e.xmppHost}`,
      `ETHORA_XMPP_WS=${e.xmppWebSocket}`, `ETHORA_XMPP_BOSH=${e.xmppBosh || ''}`, `ETHORA_XMPP_CONFERENCE=${e.xmppConference}`,
      profile.webAppUrl ? `ETHORA_WEB_APP_URL=${profile.webAppUrl}` : '', '',
    ].filter((l) => l !== undefined).join('\n');
    const p = join(dir, '.env.ethora'); writeFileSync(p, content); written.push(p); ensureGitignore('.env.ethora'); break;
  }
  case 'rn': {
    const p = join(dir, 'src', 'ethora.config.ts');
    mkdirSync(dirname(p), { recursive: true });
    const content = `// Ethora chat configuration (generated by the ethora-skill).
// Public values only — the app secret must stay on your backend.
export const ETHORA = {
  appId: '${profile.appId}',
  appToken: '${profile.appToken}',
  apiUrl: '${apiOrigin}',
  xmppHost: '${xmppHost}',
  xmppConference: '${e.xmppConference}',
  // Where your backend mints the client JWT for the signed-in user (see references/auth-modes.md)
  tokenEndpoint: '/api/ethora/token',${devJwt ? `\n  // DEV ONLY — a pre-signed client JWT for a test user. Remove before release.\n  devClientJwt: '${devJwt}',` : ''}
} as const;
`;
    writeFileSync(p, content); written.push(p); break;
  }
  default:
    console.error(`Unknown target ${target}`); process.exit(1);
}
for (const w of written) console.log(`✔ wrote ${w}`);
if ((target === 'next' || target === 'backend') && !profile.appSecret) console.log('⚠ profile has no appSecret — ETHORA_APP_SECRET is empty. Copy it from the admin panel (Settings → API) and run: node ethora-admin.mjs set-secret <secret>, then re-run write-env.');
